package name.event.web.model;
// Generated 14 Aug, 2014 5:14:05 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer icategory;
     private String name;
     private String desc;
     private Date createdOn;
     private Integer createdBy;
     private Date modifiedOn;
     private Integer modifiedBy;
     private Set events = new HashSet(0);

    public Category() {
    }

	
    public Category(String name) {
        this.name = name;
    }
    public Category(String name, String desc, Date createdOn, Integer createdBy, Date modifiedOn, Integer modifiedBy, Set events) {
       this.name = name;
       this.desc = desc;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.modifiedOn = modifiedOn;
       this.modifiedBy = modifiedBy;
       this.events = events;
    }
   
    public Integer getIcategory() {
        return this.icategory;
    }
    
    public void setIcategory(Integer icategory) {
        this.icategory = icategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }
    
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }




}


