package name.event.web.model;
// Generated 14 Aug, 2014 5:14:05 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer ievent;
     private User user;
     private Category category;
     private String name;
     private String description;
     private String organizer;
     private String website;
     private Date startDate;
     private Date endDate;
     private String addLine1;
     private String addLine2;
     private String city;
     private String region;
     private Integer postalCode;
     private String country;
     private Character active;
     private Date createdOn;
     private Integer createdBy;
     private Date modifiedOn;
     private Integer modifiedBy;

    public Event() {
    }

	
    public Event(User user, Category category, String name, String description, String organizer, String website, Date startDate) {
        this.user = user;
        this.category = category;
        this.name = name;
        this.description = description;
        this.organizer = organizer;
        this.website = website;
        this.startDate = startDate;
    }
    public Event(User user, Category category, String name, String description, String organizer, String website, Date startDate, Date endDate, String addLine1, String addLine2, String city, String region, Integer postalCode, String country, Character active, Date createdOn, Integer createdBy, Date modifiedOn, Integer modifiedBy) {
       this.user = user;
       this.category = category;
       this.name = name;
       this.description = description;
       this.organizer = organizer;
       this.website = website;
       this.startDate = startDate;
       this.endDate = endDate;
       this.addLine1 = addLine1;
       this.addLine2 = addLine2;
       this.city = city;
       this.region = region;
       this.postalCode = postalCode;
       this.country = country;
       this.active = active;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.modifiedOn = modifiedOn;
       this.modifiedBy = modifiedBy;
    }
   
    public Integer getIevent() {
        return this.ievent;
    }
    
    public void setIevent(Integer ievent) {
        this.ievent = ievent;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getOrganizer() {
        return this.organizer;
    }
    
    public void setOrganizer(String organizer) {
        this.organizer = organizer;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getAddLine1() {
        return this.addLine1;
    }
    
    public void setAddLine1(String addLine1) {
        this.addLine1 = addLine1;
    }
    public String getAddLine2() {
        return this.addLine2;
    }
    
    public void setAddLine2(String addLine2) {
        this.addLine2 = addLine2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public Integer getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(Integer postalCode) {
        this.postalCode = postalCode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Character getActive() {
        return this.active;
    }
    
    public void setActive(Character active) {
        this.active = active;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }
    
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }




}


