package name.event.web.model;
// Generated 14 Aug, 2014 5:14:05 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Follow generated by hbm2java
 */
public class Follow  implements java.io.Serializable {


     private Integer ifollow;
     private int ievent;
     private int iuser;
     private Date createdOn;
     private Integer createdBy;
     private Date modifiedOn;
     private Integer modifiedBy;

    public Follow() {
    }

	
    public Follow(int ievent, int iuser) {
        this.ievent = ievent;
        this.iuser = iuser;
    }
    public Follow(int ievent, int iuser, Date createdOn, Integer createdBy, Date modifiedOn, Integer modifiedBy) {
       this.ievent = ievent;
       this.iuser = iuser;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.modifiedOn = modifiedOn;
       this.modifiedBy = modifiedBy;
    }
   
    public Integer getIfollow() {
        return this.ifollow;
    }
    
    public void setIfollow(Integer ifollow) {
        this.ifollow = ifollow;
    }
    public int getIevent() {
        return this.ievent;
    }
    
    public void setIevent(int ievent) {
        this.ievent = ievent;
    }
    public int getIuser() {
        return this.iuser;
    }
    
    public void setIuser(int iuser) {
        this.iuser = iuser;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }
    
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }




}


